config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'
  root 'visitors#index'

  get 'visitors/easy'

  get 'visitors/difficult'

  get 'visitors/cheap'
  get 'visitors/chef1'
  get 'visitors/chef2'
  get 'visitors/chef3'
  get 'recipes/show'

  resources :recipes

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  validates :name, presence:true, length: {maximum: 30}
  validates :stars, presence:true
  has_many :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  validates :title, presence:true, length:{maximum: 50}
  validates :ingredients, presence:true
  validates :directions, presence:true
  validates :time, presence:true
  validates :difficulty, presence:true
  validates :output, presence:true
  validates :genre, presence:true
  validates :cost, presence:true
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipes = Recipe.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
#   def findchef
#     @chef = Recipe.find(params[:chef_id])
#   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :directions, :time, :difficulty, :output, :genre, :cost, :chef_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def easy
    @recipes = Recipe.all
  end

  def difficult
    @recipes = Recipe.all
  end

  def cheap
    @recipes = Recipe.all
  end
  
  def chef1
    @recipes = Recipe.all
    @chef = Chef.find_by(id: 1)
  end
  def chef2
    @recipes = Recipe.all
    @chef = Chef.find_by(id: 2)
  end
  def chef3
    @recipes = Recipe.all
    @chef = Chef.find_by(id: 3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalMichaelSpier</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">YummyTummy</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
          <li><%= link_to "Home", :controller => "visitors", :action => "index" %></li>
          <li><%= link_to "Easy Recipes", :controller => "visitors", :action => "easy" %></li>
          <li><%= link_to "Challenging Recipes", :controller => "visitors", :action => "difficult" %></li>
          <li><%= link_to "Cheap Recipes", :controller => "visitors", :action => "cheap" %></li>
      </ul>
    </div>
  </div>
</nav>
  
<div>
<div class="feature">
  <ul>
    <lh>New Feature! You can now search by Chef!</lh>
    <br><br>
    <li><%= link_to "Chef Rachel's recipes", :controller => "visitors", :action => "chef1" %></li>
    <br>
    <li><%= link_to "Chef Sandra's recipes", :controller => "visitors", :action => "chef2" %></li>
    <br>
    <li><%= link_to "Chef Paula's recipes", :controller => "visitors", :action => "chef3" %></li>
  </ul>
</div>

<div class="theyield">
<%= yield %>
</div>
</div>
  
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_field :ingredients %>
  </div>
  <div class="field">
    <%= f.label :directions %><br>
    <%= f.text_area :directions %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.text_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :output %><br>
    <%= f.number_field :output %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :chef_id %><br>
    <%= f.number_field :chef_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Ingredients</th>
      <th>Directions</th>
      <th>Time</th>
      <th>Difficulty</th>
      <th>Output</th>
      <th>Genre</th>
      <th>Cost</th>
      <th>Chef</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.directions %></td>
        <td><%= recipe.time %></td>
        <td><%= recipe.difficulty %></td>
        <td><%= recipe.output %></td>
        <td><%= recipe.genre %></td>
        <td><%= recipe.cost %></td>
        <td><%= recipe.chef_id %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Directions:</strong>
  <%= @recipe.directions %>
</p>

<p>
  <strong>Time:</strong>
  <%= @recipe.time %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @recipe.difficulty %>
</p>

<p>
  <strong>Output:</strong>
  <%= @recipe.output %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @recipe.genre %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @recipe.cost %>
</p>

<p>
  <strong>Chef:</strong>
  <%= @recipe.chef_id %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/visitors/cheap.html.erb
<h1>Our cheap recipes</h1>
<% @recipes.each do |f| %>
<% x = f.cost/f.output %>
<% if x <= 3 %>
<%= f.title %> (<%= f.genre %>) by chef: <%=(Chef.find_by(id: f.chef_id).name)%>
<br><br>
<ul><%= sanitize f.ingredients %></ul>

Directions: <%= f.directions %>
<br>
<%= f.output %>, ($<%=f.cost %>)
<br><br><br>
<% else %>
<% end %>
<% end %>

app/views/visitors/chef1.html.erb
<h1>Chef <%= @chef.name %>'s recipes</h1>
<h1><% y= @chef.stars%> <%= "* "*y %></h1>
<% x=1 %>
<% @recipes.each do |f| %>
<% if x == f.chef_id %>
<%= f.title %> (<%= f.genre %>) by chef: <%=(Chef.find_by(id: f.chef_id).name)%>
<br><br>
<ul><%= sanitize f.ingredients %></ul>

Directions: <%= f.directions %>
<br>
<%= f.output %>, ($<%=f.cost %>)
<br><br><br>
<% else %>
<% end %>
<% end %>

app/views/visitors/chef2.html.erb
<h1>Chef <%= @chef.name %>'s recipes</h1>
<h1><% y= @chef.stars%> <%= "* "*y %></h1>
<% x=2 %>
<% @recipes.each do |f| %>
<% if x == f.chef_id %>
<%= f.title %> (<%= f.genre %>) by chef: <%=(Chef.find_by(id: f.chef_id).name)%>
<br><br>
<ul><%= sanitize f.ingredients %></ul>

Directions: <%= f.directions %>
<br>
<%= f.output %>, ($<%=f.cost %>)
<br><br><br>
<% else %>
<% end %>
<% end %>

app/views/visitors/chef3.html.erb
<h1>Chef <%= @chef.name %>'s recipes</h1>
<h1><% y= @chef.stars%> <%= "* "*y %></h1>
<% x=3 %>
<% @recipes.each do |f| %>
<% if x == f.chef_id %>
<%= f.title %> (<%= f.genre %>) by chef: <%=(Chef.find_by(id: f.chef_id).name)%>
<br><br>
<ul><%= sanitize f.ingredients %></ul>

Directions: <%= f.directions %>
<br>
<%= f.output %>, ($<%=f.cost %>)
<br><br><br>
<% else %>
<% end %>
<% end %>

app/views/visitors/difficult.html.erb
<h1>Our difficult recipes</h1>
<% @recipes.each do |f| %>
<% if f.difficulty == "difficult" %>
<%= f.title %> (<%= f.genre %>) by chef: <%=(Chef.find_by(id: f.chef_id).name)%>
<br><br>
<ul><%= sanitize f.ingredients %></ul>

Directions: <%= f.directions %>
<br>
<%= f.output %>, ($<%=f.cost %>)
<br><br><br>
<% else %>
<% end %>
<% end %>

app/views/visitors/easy.html.erb
<h1>Our easy recipes</h1>
<% @recipes.each do |f| %>
<% if f.difficulty == "easy" %>
<%= f.title %> (<%= f.genre %>) by chef: <%=(Chef.find_by(id: f.chef_id).name)%>
<br><br>
<ul><%= sanitize f.ingredients %></ul>

Directions: <%= f.directions %>
<br>
<%= f.output %>, ($<%=f.cost %>)
<br><br><br>
<% else %>
<% end %>
<% end %>

app/views/visitors/index.html.erb
<h1>Welcome to our recipe database</h1>
<% @recipes.each do |f| %>
<%= f.title %> (<%= f.genre %>) by chef: <%=(Chef.find_by(id: f.chef_id).name)%>
<br><br>
<ul><%= sanitize f.ingredients %></ul>

Directions: <%= f.directions %>
<br>
<%= f.output %>, ($<%=f.cost %>)
<br><br><br>
<% end %>